# Generated by Django 4.0.6 on 2022-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
